services:
  share-photos:
    image: share-photos:0.0.1
    ports:
      - "3000:3000"
    environment:
      ORIGIN: http://localhost:3000
      BODY_SIZE_LIMIT: 1000000000
      UPLOAD_FOLDER: /share-photos
    volumes:
      - /home/nodon/Apps/share-photos:/upload
